
package com.chinasofti.utils.hb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SIServicePortType", targetNamespace = "http://services.wechatWebService.iss.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SIServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.wechatWebService.iss.com")
    @RequestWrapper(localName = "getShipClaimApp", targetNamespace = "http://services.wechatWebService.iss.com", className = "com.chinasofti.utils.hb.GetShipClaimApp")
    @ResponseWrapper(localName = "getShipClaimAppResponse", targetNamespace = "http://services.wechatWebService.iss.com", className = "com.chinasofti.utils.hb.GetShipClaimAppResponse")
    public String getShipClaimApp(
        @WebParam(name = "in0", targetNamespace = "http://services.wechatWebService.iss.com")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://services.wechatWebService.iss.com")
    @RequestWrapper(localName = "getShipPoliycApp", targetNamespace = "http://services.wechatWebService.iss.com", className = "com.chinasofti.utils.hb.GetShipPoliycApp")
    @ResponseWrapper(localName = "getShipPoliycAppResponse", targetNamespace = "http://services.wechatWebService.iss.com", className = "com.chinasofti.utils.hb.GetShipPoliycAppResponse")
    public String getShipPoliycApp(
        @WebParam(name = "in0", targetNamespace = "http://services.wechatWebService.iss.com")
        String in0);

}
