
package com.chinasofti.utils.hb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SIService", targetNamespace = "http://services.wechatWebService.iss.com", wsdlLocation = "http://124.251.60.172:9088/rcTest/service/SIService?wsdl")
public class SIService
    extends Service
{

    private final static URL SISERVICE_WSDL_LOCATION;
    private final static WebServiceException SISERVICE_EXCEPTION;
    private final static QName SISERVICE_QNAME = new QName("http://services.wechatWebService.iss.com", "SIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://124.251.60.172:9088/rcTest/service/SIService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SISERVICE_WSDL_LOCATION = url;
        SISERVICE_EXCEPTION = e;
    }

    public SIService() {
        super(__getWsdlLocation(), SISERVICE_QNAME);
    }

    public SIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SISERVICE_QNAME, features);
    }

    public SIService(URL wsdlLocation) {
        super(wsdlLocation, SISERVICE_QNAME);
    }

    public SIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SISERVICE_QNAME, features);
    }

    public SIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIServicePortType
     */
    @WebEndpoint(name = "SIServiceHttpPort")
    public SIServicePortType getSIServiceHttpPort() {
        return super.getPort(new QName("http://services.wechatWebService.iss.com", "SIServiceHttpPort"), SIServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIServicePortType
     */
    @WebEndpoint(name = "SIServiceHttpPort")
    public SIServicePortType getSIServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.wechatWebService.iss.com", "SIServiceHttpPort"), SIServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SISERVICE_EXCEPTION!= null) {
            throw SISERVICE_EXCEPTION;
        }
        return SISERVICE_WSDL_LOCATION;
    }

}
