package com.limp.framework.boss.mapper.oracle;

import com.limp.framework.boss.domain.SubSystem;
import com.limp.framework.boss.domain.SubSystemExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SubSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int countByExample(SubSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int deleteByExample(SubSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int deleteByPrimaryKey(String ssmGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int insert(SubSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int insertSelective(SubSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    List<SubSystem> selectByExample(SubSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    SubSystem selectByPrimaryKey(String ssmGuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int updateByExampleSelective(@Param("record") SubSystem record, @Param("example") SubSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int updateByExample(@Param("record") SubSystem record, @Param("example") SubSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int updateByPrimaryKeySelective(SubSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_SUBSYSTEM
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    int updateByPrimaryKey(SubSystem record);

    int updateStateByPrimaryKey(@Param("uuid") String id, @Param("state") int state);

}