package com.limp.framework.boss.domain;

import com.limp.framework.core.abs.AbstractModel;

import java.util.Date;

public class SubSystem extends AbstractModel {


    private boolean child;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_NAME
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String ssmName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_MENUAPI
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String ssmMenuapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_DATAAPI
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String ssmDataapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_ELEMENTAPI
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String ssmElementapi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_CREATEDATE
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private Date ssmCreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_UPDATETIME
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private Date ssmUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.SSM_STATE
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private Integer ssmState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.MUD_RC0
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String mudRc0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.MUD_RC1
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String mudRc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.MUD_RC2
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private String mudRc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.MUD_RC3
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private Integer mudRc3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.MUD_RC4
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private Integer mudRc4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_SUBSYSTEM.MUD_RC5
     *
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    private Date mudRc5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_NAME
     *
     * @return the value of SYS_SUBSYSTEM.SSM_NAME
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getSsmName() {
        return ssmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_NAME
     *
     * @param ssmName the value for SYS_SUBSYSTEM.SSM_NAME
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmName(String ssmName) {
        this.ssmName = ssmName == null ? null : ssmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_MENUAPI
     *
     * @return the value of SYS_SUBSYSTEM.SSM_MENUAPI
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getSsmMenuapi() {
        return ssmMenuapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_MENUAPI
     *
     * @param ssmMenuapi the value for SYS_SUBSYSTEM.SSM_MENUAPI
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmMenuapi(String ssmMenuapi) {
        this.ssmMenuapi = ssmMenuapi == null ? null : ssmMenuapi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_DATAAPI
     *
     * @return the value of SYS_SUBSYSTEM.SSM_DATAAPI
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getSsmDataapi() {
        return ssmDataapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_DATAAPI
     *
     * @param ssmDataapi the value for SYS_SUBSYSTEM.SSM_DATAAPI
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmDataapi(String ssmDataapi) {
        this.ssmDataapi = ssmDataapi == null ? null : ssmDataapi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_ELEMENTAPI
     *
     * @return the value of SYS_SUBSYSTEM.SSM_ELEMENTAPI
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getSsmElementapi() {
        return ssmElementapi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_ELEMENTAPI
     *
     * @param ssmElementapi the value for SYS_SUBSYSTEM.SSM_ELEMENTAPI
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmElementapi(String ssmElementapi) {
        this.ssmElementapi = ssmElementapi == null ? null : ssmElementapi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_CREATEDATE
     *
     * @return the value of SYS_SUBSYSTEM.SSM_CREATEDATE
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public Date getSsmCreatedate() {
        return ssmCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_CREATEDATE
     *
     * @param ssmCreatedate the value for SYS_SUBSYSTEM.SSM_CREATEDATE
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmCreatedate(Date ssmCreatedate) {
        this.ssmCreatedate = ssmCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_UPDATETIME
     *
     * @return the value of SYS_SUBSYSTEM.SSM_UPDATETIME
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public Date getSsmUpdatetime() {
        return ssmUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_UPDATETIME
     *
     * @param ssmUpdatetime the value for SYS_SUBSYSTEM.SSM_UPDATETIME
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmUpdatetime(Date ssmUpdatetime) {
        this.ssmUpdatetime = ssmUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.SSM_STATE
     *
     * @return the value of SYS_SUBSYSTEM.SSM_STATE
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public Integer getSsmState() {
        return ssmState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.SSM_STATE
     *
     * @param ssmState the value for SYS_SUBSYSTEM.SSM_STATE
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setSsmState(Integer ssmState) {
        this.ssmState = ssmState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.MUD_RC0
     *
     * @return the value of SYS_SUBSYSTEM.MUD_RC0
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getMudRc0() {
        return mudRc0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.MUD_RC0
     *
     * @param mudRc0 the value for SYS_SUBSYSTEM.MUD_RC0
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setMudRc0(String mudRc0) {
        this.mudRc0 = mudRc0 == null ? null : mudRc0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.MUD_RC1
     *
     * @return the value of SYS_SUBSYSTEM.MUD_RC1
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getMudRc1() {
        return mudRc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.MUD_RC1
     *
     * @param mudRc1 the value for SYS_SUBSYSTEM.MUD_RC1
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setMudRc1(String mudRc1) {
        this.mudRc1 = mudRc1 == null ? null : mudRc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.MUD_RC2
     *
     * @return the value of SYS_SUBSYSTEM.MUD_RC2
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public String getMudRc2() {
        return mudRc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.MUD_RC2
     *
     * @param mudRc2 the value for SYS_SUBSYSTEM.MUD_RC2
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setMudRc2(String mudRc2) {
        this.mudRc2 = mudRc2 == null ? null : mudRc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.MUD_RC3
     *
     * @return the value of SYS_SUBSYSTEM.MUD_RC3
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public Integer getMudRc3() {
        return mudRc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.MUD_RC3
     *
     * @param mudRc3 the value for SYS_SUBSYSTEM.MUD_RC3
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setMudRc3(Integer mudRc3) {
        this.mudRc3 = mudRc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.MUD_RC4
     *
     * @return the value of SYS_SUBSYSTEM.MUD_RC4
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public Integer getMudRc4() {
        return mudRc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.MUD_RC4
     *
     * @param mudRc4 the value for SYS_SUBSYSTEM.MUD_RC4
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setMudRc4(Integer mudRc4) {
        this.mudRc4 = mudRc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_SUBSYSTEM.MUD_RC5
     *
     * @return the value of SYS_SUBSYSTEM.MUD_RC5
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public Date getMudRc5() {
        return mudRc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_SUBSYSTEM.MUD_RC5
     *
     * @param mudRc5 the value for SYS_SUBSYSTEM.MUD_RC5
     * @mbggenerated Thu Jun 13 13:55:06 CST 2013
     */
    public void setMudRc5(Date mudRc5) {
        this.mudRc5 = mudRc5;
    }

    public boolean isChild() {
        return child;
    }

    public void setChild(boolean child) {
        this.child = child;
    }

    @Override
    public String toString() {
        return "SubSystem{" +
                "child=" + child +
                ", ssmName='" + ssmName + '\'' +
                ", ssmMenuapi='" + ssmMenuapi + '\'' +
                ", ssmDataapi='" + ssmDataapi + '\'' +
                ", ssmElementapi='" + ssmElementapi + '\'' +
                ", ssmCreatedate=" + ssmCreatedate +
                ", ssmUpdatetime=" + ssmUpdatetime +
                ", ssmState=" + ssmState +
                ", mudRc0='" + mudRc0 + '\'' +
                ", mudRc1='" + mudRc1 + '\'' +
                ", mudRc2='" + mudRc2 + '\'' +
                ", mudRc3=" + mudRc3 +
                ", mudRc4=" + mudRc4 +
                ", mudRc5=" + mudRc5 +
                '}';
    }
}