package com.limp.framework.boss.domain;

import com.limp.framework.core.bean.Pager;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class UserGroupExample {

    protected String orderByClause;

    protected boolean distinct;

    protected Pager page;

    protected List<Criteria> oredCriteria;

    public UserGroupExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }


    public void setPage(Pager page) {
        this.page = page;
    }

    public Pager getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("UGP_GUID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("UGP_GUID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("UGP_GUID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("UGP_GUID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("UGP_GUID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("UGP_GUID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("UGP_GUID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("UGP_GUID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("UGP_GUID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("UGP_GUID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("UGP_GUID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("UGP_GUID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("UGP_GUID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("UGP_GUID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUgpNameIsNull() {
            addCriterion("UGP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUgpNameIsNotNull() {
            addCriterion("UGP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUgpNameEqualTo(String value) {
            addCriterion("UGP_NAME =", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameNotEqualTo(String value) {
            addCriterion("UGP_NAME <>", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameGreaterThan(String value) {
            addCriterion("UGP_NAME >", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameGreaterThanOrEqualTo(String value) {
            addCriterion("UGP_NAME >=", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameLessThan(String value) {
            addCriterion("UGP_NAME <", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameLessThanOrEqualTo(String value) {
            addCriterion("UGP_NAME <=", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameLike(String value) {
            addCriterion("UGP_NAME like", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameNotLike(String value) {
            addCriterion("UGP_NAME not like", value, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameIn(List<String> values) {
            addCriterion("UGP_NAME in", values, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameNotIn(List<String> values) {
            addCriterion("UGP_NAME not in", values, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameBetween(String value1, String value2) {
            addCriterion("UGP_NAME between", value1, value2, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpNameNotBetween(String value1, String value2) {
            addCriterion("UGP_NAME not between", value1, value2, "ugpName");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidIsNull() {
            addCriterion("UGP_PARENTGUID is null");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidIsNotNull() {
            addCriterion("UGP_PARENTGUID is not null");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidEqualTo(String value) {
            addCriterion("UGP_PARENTGUID =", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidNotEqualTo(String value) {
            addCriterion("UGP_PARENTGUID <>", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidGreaterThan(String value) {
            addCriterion("UGP_PARENTGUID >", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidGreaterThanOrEqualTo(String value) {
            addCriterion("UGP_PARENTGUID >=", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidLessThan(String value) {
            addCriterion("UGP_PARENTGUID <", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidLessThanOrEqualTo(String value) {
            addCriterion("UGP_PARENTGUID <=", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidLike(String value) {
            addCriterion("UGP_PARENTGUID like", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidNotLike(String value) {
            addCriterion("UGP_PARENTGUID not like", value, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidIn(List<String> values) {
            addCriterion("UGP_PARENTGUID in", values, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidNotIn(List<String> values) {
            addCriterion("UGP_PARENTGUID not in", values, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidBetween(String value1, String value2) {
            addCriterion("UGP_PARENTGUID between", value1, value2, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpParentguidNotBetween(String value1, String value2) {
            addCriterion("UGP_PARENTGUID not between", value1, value2, "ugpParentguid");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksIsNull() {
            addCriterion("UGP_REMARKS is null");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksIsNotNull() {
            addCriterion("UGP_REMARKS is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksEqualTo(String value) {
            addCriterion("UGP_REMARKS =", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksNotEqualTo(String value) {
            addCriterion("UGP_REMARKS <>", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksGreaterThan(String value) {
            addCriterion("UGP_REMARKS >", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("UGP_REMARKS >=", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksLessThan(String value) {
            addCriterion("UGP_REMARKS <", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksLessThanOrEqualTo(String value) {
            addCriterion("UGP_REMARKS <=", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksLike(String value) {
            addCriterion("UGP_REMARKS like", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksNotLike(String value) {
            addCriterion("UGP_REMARKS not like", value, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksIn(List<String> values) {
            addCriterion("UGP_REMARKS in", values, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksNotIn(List<String> values) {
            addCriterion("UGP_REMARKS not in", values, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksBetween(String value1, String value2) {
            addCriterion("UGP_REMARKS between", value1, value2, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpRemarksNotBetween(String value1, String value2) {
            addCriterion("UGP_REMARKS not between", value1, value2, "ugpRemarks");
            return (Criteria) this;
        }

        public Criteria andUgpStateIsNull() {
            addCriterion("UGP_STATE is null");
            return (Criteria) this;
        }

        public Criteria andUgpStateIsNotNull() {
            addCriterion("UGP_STATE is not null");
            return (Criteria) this;
        }

        public Criteria andUgpStateEqualTo(Integer value) {
            addCriterion("UGP_STATE =", value, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateNotEqualTo(Integer value) {
            addCriterion("UGP_STATE <>", value, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateGreaterThan(Integer value) {
            addCriterion("UGP_STATE >", value, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("UGP_STATE >=", value, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateLessThan(Integer value) {
            addCriterion("UGP_STATE <", value, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateLessThanOrEqualTo(Integer value) {
            addCriterion("UGP_STATE <=", value, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateIn(List<Integer> values) {
            addCriterion("UGP_STATE in", values, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateNotIn(List<Integer> values) {
            addCriterion("UGP_STATE not in", values, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateBetween(Integer value1, Integer value2) {
            addCriterion("UGP_STATE between", value1, value2, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpStateNotBetween(Integer value1, Integer value2) {
            addCriterion("UGP_STATE not between", value1, value2, "ugpState");
            return (Criteria) this;
        }

        public Criteria andUgpRc0IsNull() {
            addCriterion("UGP_RC0 is null");
            return (Criteria) this;
        }

        public Criteria andUgpRc0IsNotNull() {
            addCriterion("UGP_RC0 is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRc0EqualTo(String value) {
            addCriterion("UGP_RC0 =", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0NotEqualTo(String value) {
            addCriterion("UGP_RC0 <>", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0GreaterThan(String value) {
            addCriterion("UGP_RC0 >", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0GreaterThanOrEqualTo(String value) {
            addCriterion("UGP_RC0 >=", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0LessThan(String value) {
            addCriterion("UGP_RC0 <", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0LessThanOrEqualTo(String value) {
            addCriterion("UGP_RC0 <=", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0Like(String value) {
            addCriterion("UGP_RC0 like", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0NotLike(String value) {
            addCriterion("UGP_RC0 not like", value, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0In(List<String> values) {
            addCriterion("UGP_RC0 in", values, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0NotIn(List<String> values) {
            addCriterion("UGP_RC0 not in", values, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0Between(String value1, String value2) {
            addCriterion("UGP_RC0 between", value1, value2, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc0NotBetween(String value1, String value2) {
            addCriterion("UGP_RC0 not between", value1, value2, "ugpRc0");
            return (Criteria) this;
        }

        public Criteria andUgpRc1IsNull() {
            addCriterion("UGP_RC1 is null");
            return (Criteria) this;
        }

        public Criteria andUgpRc1IsNotNull() {
            addCriterion("UGP_RC1 is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRc1EqualTo(String value) {
            addCriterion("UGP_RC1 =", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1NotEqualTo(String value) {
            addCriterion("UGP_RC1 <>", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1GreaterThan(String value) {
            addCriterion("UGP_RC1 >", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1GreaterThanOrEqualTo(String value) {
            addCriterion("UGP_RC1 >=", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1LessThan(String value) {
            addCriterion("UGP_RC1 <", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1LessThanOrEqualTo(String value) {
            addCriterion("UGP_RC1 <=", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1Like(String value) {
            addCriterion("UGP_RC1 like", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1NotLike(String value) {
            addCriterion("UGP_RC1 not like", value, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1In(List<String> values) {
            addCriterion("UGP_RC1 in", values, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1NotIn(List<String> values) {
            addCriterion("UGP_RC1 not in", values, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1Between(String value1, String value2) {
            addCriterion("UGP_RC1 between", value1, value2, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc1NotBetween(String value1, String value2) {
            addCriterion("UGP_RC1 not between", value1, value2, "ugpRc1");
            return (Criteria) this;
        }

        public Criteria andUgpRc2IsNull() {
            addCriterion("UGP_RC2 is null");
            return (Criteria) this;
        }

        public Criteria andUgpRc2IsNotNull() {
            addCriterion("UGP_RC2 is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRc2EqualTo(String value) {
            addCriterion("UGP_RC2 =", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2NotEqualTo(String value) {
            addCriterion("UGP_RC2 <>", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2GreaterThan(String value) {
            addCriterion("UGP_RC2 >", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2GreaterThanOrEqualTo(String value) {
            addCriterion("UGP_RC2 >=", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2LessThan(String value) {
            addCriterion("UGP_RC2 <", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2LessThanOrEqualTo(String value) {
            addCriterion("UGP_RC2 <=", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2Like(String value) {
            addCriterion("UGP_RC2 like", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2NotLike(String value) {
            addCriterion("UGP_RC2 not like", value, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2In(List<String> values) {
            addCriterion("UGP_RC2 in", values, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2NotIn(List<String> values) {
            addCriterion("UGP_RC2 not in", values, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2Between(String value1, String value2) {
            addCriterion("UGP_RC2 between", value1, value2, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc2NotBetween(String value1, String value2) {
            addCriterion("UGP_RC2 not between", value1, value2, "ugpRc2");
            return (Criteria) this;
        }

        public Criteria andUgpRc3IsNull() {
            addCriterion("UGP_RC3 is null");
            return (Criteria) this;
        }

        public Criteria andUgpRc3IsNotNull() {
            addCriterion("UGP_RC3 is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRc3EqualTo(Integer value) {
            addCriterion("UGP_RC3 =", value, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3NotEqualTo(Integer value) {
            addCriterion("UGP_RC3 <>", value, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3GreaterThan(Integer value) {
            addCriterion("UGP_RC3 >", value, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3GreaterThanOrEqualTo(Integer value) {
            addCriterion("UGP_RC3 >=", value, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3LessThan(Integer value) {
            addCriterion("UGP_RC3 <", value, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3LessThanOrEqualTo(Integer value) {
            addCriterion("UGP_RC3 <=", value, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3In(List<Integer> values) {
            addCriterion("UGP_RC3 in", values, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3NotIn(List<Integer> values) {
            addCriterion("UGP_RC3 not in", values, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3Between(Integer value1, Integer value2) {
            addCriterion("UGP_RC3 between", value1, value2, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc3NotBetween(Integer value1, Integer value2) {
            addCriterion("UGP_RC3 not between", value1, value2, "ugpRc3");
            return (Criteria) this;
        }

        public Criteria andUgpRc4IsNull() {
            addCriterion("UGP_RC4 is null");
            return (Criteria) this;
        }

        public Criteria andUgpRc4IsNotNull() {
            addCriterion("UGP_RC4 is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRc4EqualTo(Integer value) {
            addCriterion("UGP_RC4 =", value, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4NotEqualTo(Integer value) {
            addCriterion("UGP_RC4 <>", value, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4GreaterThan(Integer value) {
            addCriterion("UGP_RC4 >", value, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4GreaterThanOrEqualTo(Integer value) {
            addCriterion("UGP_RC4 >=", value, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4LessThan(Integer value) {
            addCriterion("UGP_RC4 <", value, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4LessThanOrEqualTo(Integer value) {
            addCriterion("UGP_RC4 <=", value, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4In(List<Integer> values) {
            addCriterion("UGP_RC4 in", values, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4NotIn(List<Integer> values) {
            addCriterion("UGP_RC4 not in", values, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4Between(Integer value1, Integer value2) {
            addCriterion("UGP_RC4 between", value1, value2, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc4NotBetween(Integer value1, Integer value2) {
            addCriterion("UGP_RC4 not between", value1, value2, "ugpRc4");
            return (Criteria) this;
        }

        public Criteria andUgpRc5IsNull() {
            addCriterion("UGP_RC5 is null");
            return (Criteria) this;
        }

        public Criteria andUgpRc5IsNotNull() {
            addCriterion("UGP_RC5 is not null");
            return (Criteria) this;
        }

        public Criteria andUgpRc5EqualTo(Date value) {
            addCriterionForJDBCDate("UGP_RC5 =", value, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5NotEqualTo(Date value) {
            addCriterionForJDBCDate("UGP_RC5 <>", value, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5GreaterThan(Date value) {
            addCriterionForJDBCDate("UGP_RC5 >", value, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5GreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UGP_RC5 >=", value, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5LessThan(Date value) {
            addCriterionForJDBCDate("UGP_RC5 <", value, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5LessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("UGP_RC5 <=", value, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5In(List<Date> values) {
            addCriterionForJDBCDate("UGP_RC5 in", values, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5NotIn(List<Date> values) {
            addCriterionForJDBCDate("UGP_RC5 not in", values, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5Between(Date value1, Date value2) {
            addCriterionForJDBCDate("UGP_RC5 between", value1, value2, "ugpRc5");
            return (Criteria) this;
        }

        public Criteria andUgpRc5NotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("UGP_RC5 not between", value1, value2, "ugpRc5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 20 11:55:59 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SYS_USERGROUP
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}