package com.limp.framework.boss.domain;

import com.limp.framework.core.abs.AbstractModel;

import java.util.Date;

public class UserGroup extends AbstractModel {

    private int child;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_GUID
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_NAME
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String ugpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_PARENTGUID
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String ugpParentguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_REMARKS
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String ugpRemarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_STATE
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private Integer ugpState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_RC0
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String ugpRc0;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_RC1
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String ugpRc1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_RC2
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private String ugpRc2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_RC3
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private Integer ugpRc3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_RC4
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private Integer ugpRc4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_USERGROUP.UGP_RC5
     *
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    private Date ugpRc5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_GUID
     *
     * @return the value of SYS_USERGROUP.UGP_GUID
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_GUID
     *
     * @param id the value for SYS_USERGROUP.UGP_GUID
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_NAME
     *
     * @return the value of SYS_USERGROUP.UGP_NAME
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getUgpName() {
        return ugpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_NAME
     *
     * @param ugpName the value for SYS_USERGROUP.UGP_NAME
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpName(String ugpName) {
        this.ugpName = ugpName == null ? null : ugpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_PARENTGUID
     *
     * @return the value of SYS_USERGROUP.UGP_PARENTGUID
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getUgpParentguid() {
        return ugpParentguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_PARENTGUID
     *
     * @param ugpParentguid the value for SYS_USERGROUP.UGP_PARENTGUID
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpParentguid(String ugpParentguid) {
        this.ugpParentguid = ugpParentguid == null ? null : ugpParentguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_REMARKS
     *
     * @return the value of SYS_USERGROUP.UGP_REMARKS
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getUgpRemarks() {
        return ugpRemarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_REMARKS
     *
     * @param ugpRemarks the value for SYS_USERGROUP.UGP_REMARKS
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRemarks(String ugpRemarks) {
        this.ugpRemarks = ugpRemarks == null ? null : ugpRemarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_STATE
     *
     * @return the value of SYS_USERGROUP.UGP_STATE
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public Integer getUgpState() {
        return ugpState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_STATE
     *
     * @param ugpState the value for SYS_USERGROUP.UGP_STATE
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpState(Integer ugpState) {
        this.ugpState = ugpState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_RC0
     *
     * @return the value of SYS_USERGROUP.UGP_RC0
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getUgpRc0() {
        return ugpRc0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_RC0
     *
     * @param ugpRc0 the value for SYS_USERGROUP.UGP_RC0
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRc0(String ugpRc0) {
        this.ugpRc0 = ugpRc0 == null ? null : ugpRc0.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_RC1
     *
     * @return the value of SYS_USERGROUP.UGP_RC1
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getUgpRc1() {
        return ugpRc1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_RC1
     *
     * @param ugpRc1 the value for SYS_USERGROUP.UGP_RC1
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRc1(String ugpRc1) {
        this.ugpRc1 = ugpRc1 == null ? null : ugpRc1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_RC2
     *
     * @return the value of SYS_USERGROUP.UGP_RC2
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public String getUgpRc2() {
        return ugpRc2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_RC2
     *
     * @param ugpRc2 the value for SYS_USERGROUP.UGP_RC2
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRc2(String ugpRc2) {
        this.ugpRc2 = ugpRc2 == null ? null : ugpRc2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_RC3
     *
     * @return the value of SYS_USERGROUP.UGP_RC3
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public Integer getUgpRc3() {
        return ugpRc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_RC3
     *
     * @param ugpRc3 the value for SYS_USERGROUP.UGP_RC3
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRc3(Integer ugpRc3) {
        this.ugpRc3 = ugpRc3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_RC4
     *
     * @return the value of SYS_USERGROUP.UGP_RC4
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public Integer getUgpRc4() {
        return ugpRc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_RC4
     *
     * @param ugpRc4 the value for SYS_USERGROUP.UGP_RC4
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRc4(Integer ugpRc4) {
        this.ugpRc4 = ugpRc4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_USERGROUP.UGP_RC5
     *
     * @return the value of SYS_USERGROUP.UGP_RC5
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public Date getUgpRc5() {
        return ugpRc5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_USERGROUP.UGP_RC5
     *
     * @param ugpRc5 the value for SYS_USERGROUP.UGP_RC5
     * @mbggenerated Thu Jun 20 11:55:59 CST 2013
     */
    public void setUgpRc5(Date ugpRc5) {
        this.ugpRc5 = ugpRc5;
    }


    public int getChild() {
        return child;
    }

    public void setChild(int child) {
        this.child = child;
    }

    @Override
    public String toString() {
        return "UserGroup{" +
                "child=" + child +
                ", id='" + id + '\'' +
                ", ugpName='" + ugpName + '\'' +
                ", ugpParentguid='" + ugpParentguid + '\'' +
                ", ugpRemarks='" + ugpRemarks + '\'' +
                ", ugpState=" + ugpState +
                ", ugpRc0='" + ugpRc0 + '\'' +
                ", ugpRc1='" + ugpRc1 + '\'' +
                ", ugpRc2='" + ugpRc2 + '\'' +
                ", ugpRc3=" + ugpRc3 +
                ", ugpRc4=" + ugpRc4 +
                ", ugpRc5=" + ugpRc5 +
                '}';
    }
}